spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservice?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
  activemq:
    broker-url: tcp://localhost:61617

  mail:
    host: smtp.yeah.net
    username: xxx
    password: xxx
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttle:
            enable: true
            required: true

lance:
  mail:
    sender: xxx@xxx.net

logging:
  level:
    root: debug