server:
  port: 8081
  servlet:
    context-path: /

spring:
  mail:
    host: smtp.yeah.net
    username: xxx
    password: xxx
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttle:
            enable: true
            required: true

lance:
  mail:
    sender: xxx@xxx.net

logging:
  level:
    root: debug

